name: TestPyPI
on:
  pull_request:
    paths:
      - 'src/**'
      - 'pyproject.toml'
jobs:
  test_pypi:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: >-
          uv version --bump patch && version=$(uv version | awk '{print $2}') && uv version $version.dev.$(date +%s)
      - run: uv build
      - run: uv publish --index testpypi
